# Generated by Django 4.2.16 on 2024-10-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_teststock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestStock',
        ),
    ]
